apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: xotomicro-front-user-service
  name: xotomicro-front-user-service
spec:
  ports:
    - name: "7074"
      port: 7074
      targetPort: 80
  selector:
    io.kompose.service: xotomicro-front-user-service
status:
  loadBalancer: {}
